---
title: "For loop"
author: "Yu"
date: "2019.10.10"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE }
knitr::opts_chunk$set(echo = TRUE)
```


# for循环句法： for(var in seq) {exp}
```{r}  
for (x in 1:10) {
  print(x)
}  
```
###上面例子中，1:10是一个序列，可以单独输入，注意: 为英文输入！！在Consol里试一试

# 常见应用（一）
```{r}
values=c(3,5,9)
for (v in values ) {
  print(v)
}  
```
###{}中的code 对values的每一个值都run一遍，即循环run

# 常见应用（二）：求1~100之间所有数的和
```{r}
sum <- 0  #提前定义object，并赋值为0
for(i in 1:100){
  sum = sum + i
}
print(sum)
```

# 常见应用（三）：求二维数组中的最大值
```{r}
ar=array(1:9,c(3,3))  #3X3 array
ar
maxv<-ar[1,1]   #假定第一个是最大值
for (i in 1:3) {
  for (j in 1:3) {
    if(ar[i,j]>maxv)
    maxv<-ar[i,j] 
  }
}
print(maxv)
```
###ar=array(1:9,c(3,3))  #构造3X3 数组array
###maxv<-ar[1,1]   假定第一个是最大值


# 常见应用（四）：求Fibonacci序列的前N项(N=10)
```{r}
F<-NA  
F[1]<-1
F[2]<-1  
for (n in 3:10) {
  F[n]<-F[n-1]+F[n-2]
}
print(F)
```
## 1 for the first two values； Q：what happens if the second value is 2?
